# Generated by Django 3.0.3 on 2020-07-12 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0003_auto_20200713_0149'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='userName',
        ),
        migrations.RemoveField(
            model_name='user',
            name='userPassword',
        ),
        migrations.AddField(
            model_name='user',
            name='name',
            field=models.CharField(default='0000', max_length=20, verbose_name='用户名'),
        ),
        migrations.AddField(
            model_name='user',
            name='password',
            field=models.CharField(default='0000', max_length=20, verbose_name='用户密码'),
        ),
        migrations.AddField(
            model_name='user',
            name='roles',
            field=models.ManyToManyField(to='weather.Role'),
        ),
        migrations.AlterField(
            model_name='user',
            name='userID',
            field=models.CharField(default='0000', max_length=8, verbose_name='用户ID'),
        ),
    ]
